### ISSUE TITLE
Map maker docs

### ISSUE THREAD

**Issue by ASoothingEbb** [ASoothingEbb/Clue#23]
How are maps stored in CSV

Tutorial on how to manually edit csv

Tutorial on how to use map maker

Tutorials can be short

JAVA DOCS????

I think you said you made unit tests for map maker but its probs still a good idea

**Comment by Zemiguel99** [comment]
Java Docs for this are now finished.

**Comment by Zemiguel99** [comment]
Players can make a map with rooms that have no doors. Therefore making the game impossible to win.

**Comment by ASoothingEbb** [comment]
Map maker docs have been written
