### ISSUE TITLE
Optimise actionLog

### ISSUE THREAD

**Issue by stephen-bracken** [ASoothingEbb/Clue#34]
Make actionLog more Garbage Collection friendly

**Comment by ASoothingEbb** [comment]
actionLog keeps getting bigger as the game goes on, but as this hasnt caused any issues during testing yet, assign wontfix for now

**Comment by Mathew-Wright** [comment]
This is a 'feature' that will be helpfull for ai only games

**Comment by ASoothingEbb** [comment]
> This is a 'feature' that will be helpfull for ai only games

Lies
